version: '3.3'
services:
    lgogdownloader:
        image: lukas1818/lgogdownloader
        container_name: lgogdownloader
        environment:
            - GOG_EMAIL=
            - GOG_PASSWORD=
            - INTERVALL=1d
        volumes:
            - './data:/home/user/download'
        command: --help
        restart: unless-stopped
